### ISSUE TITLE
GerritException: Error when listing files

### ISSUE THREAD

**Issue by westGit** [TouK/sputnik#110]
Hello, 

First, thanks for your work.It's a intersting project.

This is my problemes : 
i execute the job :
sputnik --conf myconf.properties --changeId I445becc2a3c339f74accfc24e7c9e30be59fd218 --revisionId f77326579f8b9e668f13182b8e4bee9dcaf5b763

Result : 
Sputnik version 1.4.0
15:05:10.608 [main] INFO  p.t.s.c.ConfigurationHolder - Initializing configuration properties from file myconf.properties
15:05:10.966 [main] INFO  p.t.s.connector.http.HttpConnector - Request  1: GET to https://gerrit.it.int:443/a/changes/I445becc2a3c339f74accfc24e7c9e30be59fd218/revisions/f77326579f8b9e668f13182b8e4bee9dcaf5b763/files/?
Exception in thread "main" pl.touk.sputnik.connector.gerrit.GerritException: Error when listing files
        at pl.touk.sputnik.connector.gerrit.GerritFacade.listFiles(GerritFacade.java:56)
        at pl.touk.sputnik.engine.Engine.run(Engine.java:23)
        at pl.touk.sputnik.Main.main(Main.java:37)
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
        at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1991)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1098)
        at sun.security.ssl.SSLSocketImpl.waitForClose(SSLSocketImpl.java:1737)
        at sun.security.ssl.HandshakeOutStream.flush(HandshakeOutStream.java:122)
        at sun.security.ssl.Handshaker.sendChangeCipherSpec(Handshaker.java:1005)
        at sun.security.ssl.ClientHandshaker.sendChangeCipherAndFinish(ClientHandshaker.java:1184)
        at sun.security.ssl.ClientHandshaker.serverHelloDone(ClientHandshaker.java:1096)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:345)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:901)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:837)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1035)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1344)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1371)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1355)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:261)
        at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:118)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:357)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:218)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:194)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at pl.touk.sputnik.connector.http.HttpConnector.logAndExecute(HttpConnector.java:47)
        at pl.touk.sputnik.connector.gerrit.GerritConnector.listFiles(GerritConnector.java:32)
        at pl.touk.sputnik.connector.gerrit.GerritFacade.listFiles(GerritFacade.java:39)
        ... 2 more

So, when i take the url to put in chrome , i got a file. Our gerrit is working with certifcate, 
My question is, can i put a parameter to add certifcate in the config? or how can i resolved my issues.

Thnaks for your help

**Comment by westGit** [comment]
hello, 

I resolved my issues. if any one interste, i will push the modification.


Have a good day

**Comment by SpOOnman** [comment]
Yes, please submit your problem and a solution so we know how to advice others in future. Thanks!

**Comment by westGit** [comment]
hello, don't think other people have my config so, i put just here my modification, you can take it if you want.

File modification : HttpHelper.java
Methode : 


   @Nullable
    private LayeredConnectionSocketFactory buildSSLSocketFactory() {
        SSLSocketFactory socketFactory = null;
        try {
            KeyStore clientKeyStore = KeyStore.getInstance("JKS");
            clientKeyStore.load(new FileInputStream(ConfigurationHolder.instance().getProperty(GeneralOption.KEYSTORE_PATH)),
                 GeneralOption.KEYSTORE_PASSWORD.toCharArray());
             socketFactory = new SSLSocketFactory(
                    SSLSocketFactory.SSL,
                    clientKeyStore,
                    GeneralOption.KEYSTORE_PASSWORD,
                    null,
                    null,
                    null,
                    (X509HostnameVerifier) SSLSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER);

        } catch (IOException e) {
            e.printStackTrace();
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        } catch (CertificateException e) {
            e.printStackTrace();
        } catch (UnrecoverableKeyException e) {
            e.printStackTrace();
        } catch (KeyStoreException e) {
            e.printStackTrace();
        } catch (KeyManagementException e) {
            e.printStackTrace();
        }
        return socketFactory;
    }


Add constant in GeneralOption.java : 
KEYSTORE_PATH("keystore.path", "keystore path", "");
KEYSTORE_PASSWORD("keystore.password", "keystore password", "");

Voilà

Hope , will help another
Thanks
