### ISSUE TITLE
Hang on sonar analysis

### ISSUE THREAD

**Issue by koral--** [TouK/sputnik#150]
sputnik output:

```
Sputnik version 1.7.3
00:49:15.100 [main] INFO  p.t.s.c.ConfigurationBuilder - Initializing configuration properties from file /opt/sputnik/sputnik.conf
00:49:15.111 [main] INFO  p.t.s.c.gerrit.GerritFacadeBuilder - Using Gerrit URL: http://localhost:8080
00:49:15.462 [main] INFO  pl.touk.sputnik.engine.ReviewRunner - Review started for processor Sonar
00:49:15.469 [main] INFO  p.t.s.processor.sonar.SonarRunner - Loading /opt/sputnik/sonar-project.properties
00:49:15.472 [main] INFO  p.t.s.processor.sonar.SonarRunner - Sonar configuration: {sonar.report.export.path=sonar-report.json, sonar.sources=., sonar.exclusions=app/build/**, sonar.scm-stats.enabled=false, sonar.projectVersion=1.0, sonar.projectKey=TestProject, sonar.verbose=true, sonar.projectBaseDir=., sonar.inclusions=**/Cat.java, **/sonar.properties, issueassignplugin.enabled=false, sonar.working.directory=.sonar, sonar.analysis.mode=incremental, sonar.scm.enabled=false, sonar.projectName=TestProject}
DEBUG: cache: /home/jenkins/.sonar/ws_cache/http%3A%2F%2Flocalhost%3A9000/global
INFO: User cache: /home/jenkins/.sonar/cache
DEBUG: Extract sonar-runner-batch in temp...
DEBUG: Get bootstrap index...
DEBUG: Download: http://localhost:9000/batch_bootstrap/index
DEBUG: Get bootstrap completed
DEBUG: Create isolated classloader...
DEBUG: Start temp cleaning...
DEBUG: Temp cleaning done
DEBUG: Execution getVersion
DEBUG: Execution start
INFO: Load global repositories
INFO: Load global repositories (done) | time=102ms
INFO: User cache: /home/jenkins/.sonar/cache
INFO: Load plugins index
INFO: Load plugins index (done) | time=3ms
INFO: Default locale: "en_US", source code encoding: "UTF-8" (analysis is platform dependent)
DEBUG: Work directory: /home/jenkins/.jenkins/jobs/TestProject-PreDevelopment/workspace/.sonar
DEBUG: Execution getVersion
DEBUG: Execution execute
INFO: Process project properties
Exception in thread "main" You must define the following mandatory properties for 'Unknown': sonar.projectKey, sonar.projectName, sonar.projectVersion, sonar.sources
```

Note that all properties from exception message are defined, its values are even listed in log above.
sputnik and sonar configs:

```
$ cat /opt/sputnik/sputnik.conf 
connector.type=gerrit
connector.host=localhost
connector.port=8080
connector.username=user
connector.password=password
sonar.enabled=true
sonar.configurationFiles=/opt/sputnik/sonar-project.properties
sonar.verbose=true
project.build.tool=gradle

$ cat /opt/sputnik/sonar-project.properties
sonar.projectKey=TestProject
sonar.projectName=TestProject
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=app/build/**
```

sonar version 5.5
sonar server is working properly and sonar config is valid, it works with SonarQube Plugin for jenkins.

**Comment by pjagielski** [comment]
Hi, is this a problem in a new 1.7.3 version or permanent?

**Comment by koral--** [comment]
Do you mean if this issue exists in versions older than 1.7.3? I haven't checked.
Not sure if it is clear, but after printing `Exception in thread "main"` sputnik hangs forever, I've waited several minutes and nothing happened.

**Comment by koral--** [comment]
I've just checked with 1.7.2 and tried also with compiled current code from master, issue is still there.
Exception is thrown here:
https://github.com/TouK/sputnik/blob/c0358d07cf1d2c25f99d8f5c98aff607ea25dc5f/src/main/java/pl/touk/sputnik/processor/sonar/SonarRunner.java#L62
and here is a stacktrace:
```
pl.touk.sputnik.review.ReviewException: SonarResultParser error
        at pl.touk.sputnik.processor.sonar.SonarProcessor.process(SonarProcessor.java:54) ~[sputnik-1.7.4-SNAPSHOT.jar:1.7.4]
        at pl.touk.sputnik.engine.ReviewRunner.review(ReviewRunner.java:25) ~[sputnik-1.7.4-SNAPSHOT.jar:1.7.4]
        at pl.touk.sputnik.engine.Engine.run(Engine.java:40) [sputnik-1.7.4-SNAPSHOT.jar:1.7.4]
        at pl.touk.sputnik.Main.main(Main.java:36) [sputnik-1.7.4-SNAPSHOT.jar:1.7.4]
Caused by: java.io.FileNotFoundException: .sonar/sonar-report.json (No such file or directory)
        at java.io.FileInputStream.open0(Native Method) ~[na:1.8.0_92]
        at java.io.FileInputStream.open(FileInputStream.java:195) ~[na:1.8.0_92]
        at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[na:1.8.0_92]
        at java.io.FileReader.<init>(FileReader.java:72) ~[na:1.8.0_92]
        at pl.touk.sputnik.processor.sonar.SonarResultParser.parseResults(SonarResultParser.java:45) ~[sputnik-1.7.4-SNAPSHOT.jar:1.7.4]
        at pl.touk.sputnik.processor.sonar.SonarProcessor.process(SonarProcessor.java:51) ~[sputnik-1.7.4-SNAPSHOT.jar:1.7.4]
        ... 3 common frames omitted
```
Indeed there is no `.sonar/sonar-report.json` file in the workspace.

**Comment by SpOOnman** [comment]
I've dropped support for SonarQube incremental analysis on 2.0.

**Comment by SpOOnman** [comment]
I've dropped support for SonarQube incremental analysis on 2.0.
