### ISSUE TITLE
authentication error: missing realm in challenge

### ISSUE THREAD

**Issue by vathanakmao** [TouK/sputnik#32]
Hi, I got the error below when trying to run sputnik command. I could access the URL successfully from browser https://gerrit-pilot.goldengekko.com:443/a/changes/I368eab9eeb91a6ccb717a960de8d0fdbe9cd8260/revisions/5b0f697deab830e493a70f564f7eee22982b2c81/files/?

17:55:18.154 [main] INFO  p.t.s.c.ConfigurationHolder - Initializing configuration properties from file config-dev.properties
17:55:18.591 [main] INFO  p.t.s.connector.http.HttpConnector - Request  1: GET to https://gerrit-pilot.goldengekko.com:443/a/changes/I368eab9eeb91a6ccb717a960de8d0fdbe9cd8260/revisions/5b0f697deab830e493a70f564f7eee22982b2c81/files/?
17:55:18.872 [main] ERROR o.a.http.impl.auth.HttpAuthenticator - DIGEST [complete=false, nonce=null, nc=0] authentication error: missing realm in challenge
17:55:18.908 [main] ERROR o.a.http.impl.auth.HttpAuthenticator - DIGEST [complete=false, nonce=null, nc=0] authentication error: missing realm in challenge
17:55:18.920 [main] INFO  p.t.s.connector.http.HttpConnector - Response 1: HTTP/1.1 401 Unauthorized
17:55:18.922 [main] INFO  p.t.s.connector.http.HttpConnector - Entity 1: Unauthorized
Exception in thread "main" pl.touk.sputnik.connector.gerrit.GerritException: Error listing files
	at pl.touk.sputnik.connector.gerrit.GerritFacade.listFiles(GerritFacade.java:51)
	at pl.touk.sputnik.review.Engine.run(Engine.java:26)
	at pl.touk.sputnik.Main.main(Main.java:37)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Unauthorized': was expecting 
 at [Source: java.io.StringReader@414f2958; line: 1, column: 25]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1524)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:557)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2042)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1412)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:679)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3024)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2971)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2091)
	at pl.touk.sputnik.connector.gerrit.GerritFacade.listFiles(GerritFacade.java:36)

**Comment by SpOOnman** [comment]
Sputnik has completely switched to @uwolfer's client so this issue is not present as of 1.4.
