### ISSUE TITLE
Sputnik crashes build

### ISSUE THREAD

**Issue by damianszczepanik** [TouK/sputnik#75]
Recently a few our builds failed because of external library which is used by Sputnik. Sputnik crashed and Jenkins marked build as failed.

Exception in thread "main" pl.touk.sputnik.connector.gerrit.GerritException: Error when listing files
	at pl.touk.sputnik.connector.gerrit.GerritFacade.listFiles(GerritFacade.java:61)
	at pl.touk.sputnik.engine.Engine.run(Engine.java:23)
	at pl.touk.sputnik.Main.main(Main.java:37)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Not': was expecting 
 at [Source: java.io.StringReader@65fa3e0; line: 1, column: 4]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1524)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:557)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2042)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2018)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._matchToken(ReaderBasedJsonParser.java:1870)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1389)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:679)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3024)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2971)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2091)
	at pl.touk.sputnik.connector.gerrit.GerritFacade.listFiles(GerritFacade.java:46)
	... 2 more
:run FAILED

FAILURE: Build failed with an exception.

I see that this library is not used any more but there is no update on maven repository. Also recent processors are not available there.

Can you make a release and to fix this crash?

**Comment by SpOOnman** [comment]
Which version did you use? Jackson has thrown an exception, because Gerrit response was not JSON. It could be some error like "Not available". So it would be a network or Gerrit problem. Did it resolve afterwards?

**Comment by damianszczepanik** [comment]
Network is fine and based on your response I believe this may happen also when there is no file to review - patch contains 0 file. It happens when you send to review patchset that was already submitted to another branch and what you have done was to merge this changes between branches and sent to gerrit. In that case I believe JSON is empty or similar.

**Comment by SpOOnman** [comment]
@damianszczepanik can you provide a fix for that?
