### ISSUE TITLE
NPE when using Sonar

### ISSUE THREAD

**Issue by polopi** [TouK/sputnik#91]
I've got the following NPE when running sonar :
```
16:16:06.332 INFO  - ANALYSIS SUCCESSFUL
Exception in thread "main" java.lang.NullPointerException
        at pl.touk.sputnik.processor.sonar.SonarResultParser.getIssueFilePath(SonarResultParser.java:126)
        at pl.touk.sputnik.processor.sonar.SonarResultParser.parseResults(SonarResultParser.java:65)
        at pl.touk.sputnik.processor.sonar.SonarProcessor.process(SonarProcessor.java:48)
        at pl.touk.sputnik.engine.ReviewRunner.review(ReviewRunner.java:24)
        at pl.touk.sputnik.engine.Engine.run(Engine.java:33)
        at pl.touk.sputnik.Main.main(Main.java:37)
```

I'm using sonar 5.1.

**Comment by polopi** [comment]
Fix in PR #92
